### PR TITLE
Add Pillow support.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by Natim** [comment]
Updated with the Pillow dependency.

**Comment by benoitc** [comment]
Thanks!The patch looks good. Can you squash the commits in once? Also maybe #8 could also be merged with that PR.

**Comment by Natim** [comment]
Yes sure.

**Comment by Natim** [comment]
Updated.

**Comment by benoitc** [comment]
merged. I will take care about the release on pypy in later in the day

**Comment by Natim** [comment]
Great thanks :)

**Pull request merged**
