### PR TITLE
Update setup.py so that it works with Python 3.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by benoitc** [comment]
Looking at that PR i see it is only supporting python 3. Some people are still using Python 2, couldn't it be made in a way to also support python 2?

**Comment by Natim** [comment]
Yes I definitely could but I guess people could still install 0.1.0 in that case, I understood 2018 trends where to remove support for Python 2.

**Comment by Natim** [comment]
I don't seem to have the rights to publish the release on pypi. Can I let you do it?

**Comment by benoitc** [comment]
i will do it, i hav epostponed it until monday. There was something strange in my latest upgrade of python that prevented it...

**Pull request merged**
